// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2c2p.Assignment.Data.Context;

namespace _2c2p.Assignment.Data.Context.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_2c2p.Assignment.Data.Model.ISO4217CurrencyCode", b =>
                {
                    b.Property<string>("V")
                        .HasColumnType("VARCHAR(8)")
                        .HasColumnName("Values");

                    b.HasKey("V");

                    b.ToTable("ISO4217CurrencyCode");

                    b.HasData(
                        new
                        {
                            V = "AED"
                        },
                        new
                        {
                            V = "AFN"
                        },
                        new
                        {
                            V = "ALL"
                        },
                        new
                        {
                            V = "AMD"
                        },
                        new
                        {
                            V = "ANG"
                        },
                        new
                        {
                            V = "AOA"
                        },
                        new
                        {
                            V = "ARS"
                        },
                        new
                        {
                            V = "AUD"
                        },
                        new
                        {
                            V = "AWG"
                        },
                        new
                        {
                            V = "AZN"
                        },
                        new
                        {
                            V = "BAM"
                        },
                        new
                        {
                            V = "BBD"
                        },
                        new
                        {
                            V = "BDT"
                        },
                        new
                        {
                            V = "BGN"
                        },
                        new
                        {
                            V = "BHD"
                        },
                        new
                        {
                            V = "BIF"
                        },
                        new
                        {
                            V = "BMD"
                        },
                        new
                        {
                            V = "BND"
                        },
                        new
                        {
                            V = "BOB"
                        },
                        new
                        {
                            V = "BOV"
                        },
                        new
                        {
                            V = "BRL"
                        },
                        new
                        {
                            V = "BSD"
                        },
                        new
                        {
                            V = "BTN"
                        },
                        new
                        {
                            V = "BWP"
                        },
                        new
                        {
                            V = "BYN"
                        },
                        new
                        {
                            V = "BZD"
                        },
                        new
                        {
                            V = "CAD"
                        },
                        new
                        {
                            V = "CDF"
                        },
                        new
                        {
                            V = "CHE"
                        },
                        new
                        {
                            V = "CHF"
                        },
                        new
                        {
                            V = "CHW"
                        },
                        new
                        {
                            V = "CLF"
                        },
                        new
                        {
                            V = "CLP"
                        },
                        new
                        {
                            V = "CNY"
                        },
                        new
                        {
                            V = "COP"
                        },
                        new
                        {
                            V = "COU"
                        },
                        new
                        {
                            V = "CRC"
                        },
                        new
                        {
                            V = "CUC"
                        },
                        new
                        {
                            V = "CUP"
                        },
                        new
                        {
                            V = "CVE"
                        },
                        new
                        {
                            V = "CZK"
                        },
                        new
                        {
                            V = "DJF"
                        },
                        new
                        {
                            V = "DKK"
                        },
                        new
                        {
                            V = "DOP"
                        },
                        new
                        {
                            V = "DZD"
                        },
                        new
                        {
                            V = "EGP"
                        },
                        new
                        {
                            V = "ERN"
                        },
                        new
                        {
                            V = "ETB"
                        },
                        new
                        {
                            V = "EUR"
                        },
                        new
                        {
                            V = "FJD"
                        },
                        new
                        {
                            V = "FKP"
                        },
                        new
                        {
                            V = "GBP"
                        },
                        new
                        {
                            V = "GEL"
                        },
                        new
                        {
                            V = "GHS"
                        },
                        new
                        {
                            V = "GIP"
                        },
                        new
                        {
                            V = "GMD"
                        },
                        new
                        {
                            V = "GNF"
                        },
                        new
                        {
                            V = "GTQ"
                        },
                        new
                        {
                            V = "GYD"
                        },
                        new
                        {
                            V = "HKD"
                        },
                        new
                        {
                            V = "HNL"
                        },
                        new
                        {
                            V = "HRK"
                        },
                        new
                        {
                            V = "HTG"
                        },
                        new
                        {
                            V = "HUF"
                        },
                        new
                        {
                            V = "IDR"
                        },
                        new
                        {
                            V = "ILS"
                        },
                        new
                        {
                            V = "INR"
                        },
                        new
                        {
                            V = "IQD"
                        },
                        new
                        {
                            V = "IRR"
                        },
                        new
                        {
                            V = "ISK"
                        },
                        new
                        {
                            V = "JMD"
                        },
                        new
                        {
                            V = "JOD"
                        },
                        new
                        {
                            V = "JPY"
                        },
                        new
                        {
                            V = "KES"
                        },
                        new
                        {
                            V = "KGS"
                        },
                        new
                        {
                            V = "KHR"
                        },
                        new
                        {
                            V = "KMF"
                        },
                        new
                        {
                            V = "KPW"
                        },
                        new
                        {
                            V = "KRW"
                        },
                        new
                        {
                            V = "KWD"
                        },
                        new
                        {
                            V = "KYD"
                        },
                        new
                        {
                            V = "KZT"
                        },
                        new
                        {
                            V = "LAK"
                        },
                        new
                        {
                            V = "LBP"
                        },
                        new
                        {
                            V = "LKR"
                        },
                        new
                        {
                            V = "LRD"
                        },
                        new
                        {
                            V = "LSL"
                        },
                        new
                        {
                            V = "LYD"
                        },
                        new
                        {
                            V = "MAD"
                        },
                        new
                        {
                            V = "MDL"
                        },
                        new
                        {
                            V = "MGA"
                        },
                        new
                        {
                            V = "MKD"
                        },
                        new
                        {
                            V = "MMK"
                        },
                        new
                        {
                            V = "MNT"
                        },
                        new
                        {
                            V = "MOP"
                        },
                        new
                        {
                            V = "MRU"
                        },
                        new
                        {
                            V = "MUR"
                        },
                        new
                        {
                            V = "MVR"
                        },
                        new
                        {
                            V = "MWK"
                        },
                        new
                        {
                            V = "MXN"
                        },
                        new
                        {
                            V = "MXV"
                        },
                        new
                        {
                            V = "MYR"
                        },
                        new
                        {
                            V = "MZN"
                        },
                        new
                        {
                            V = "NAD"
                        },
                        new
                        {
                            V = "NGN"
                        },
                        new
                        {
                            V = "NIO"
                        },
                        new
                        {
                            V = "NOK"
                        },
                        new
                        {
                            V = "NPR"
                        },
                        new
                        {
                            V = "NZD"
                        },
                        new
                        {
                            V = "OMR"
                        },
                        new
                        {
                            V = "PAB"
                        },
                        new
                        {
                            V = "PEN"
                        },
                        new
                        {
                            V = "PGK"
                        },
                        new
                        {
                            V = "PHP"
                        },
                        new
                        {
                            V = "PKR"
                        },
                        new
                        {
                            V = "PLN"
                        },
                        new
                        {
                            V = "PYG"
                        },
                        new
                        {
                            V = "QAR"
                        },
                        new
                        {
                            V = "RON"
                        },
                        new
                        {
                            V = "RSD"
                        },
                        new
                        {
                            V = "RUB"
                        },
                        new
                        {
                            V = "RWF"
                        },
                        new
                        {
                            V = "SAR"
                        },
                        new
                        {
                            V = "SBD"
                        },
                        new
                        {
                            V = "SCR"
                        },
                        new
                        {
                            V = "SDG"
                        },
                        new
                        {
                            V = "SEK"
                        },
                        new
                        {
                            V = "SGD"
                        },
                        new
                        {
                            V = "SHP"
                        },
                        new
                        {
                            V = "SLL"
                        },
                        new
                        {
                            V = "SOS"
                        },
                        new
                        {
                            V = "SRD"
                        },
                        new
                        {
                            V = "SSP"
                        },
                        new
                        {
                            V = "STN"
                        },
                        new
                        {
                            V = "SVC"
                        },
                        new
                        {
                            V = "SYP"
                        },
                        new
                        {
                            V = "SZL"
                        },
                        new
                        {
                            V = "THB"
                        },
                        new
                        {
                            V = "TJS"
                        },
                        new
                        {
                            V = "TMT"
                        },
                        new
                        {
                            V = "TND"
                        },
                        new
                        {
                            V = "TOP"
                        },
                        new
                        {
                            V = "TRY"
                        },
                        new
                        {
                            V = "TTD"
                        },
                        new
                        {
                            V = "TWD"
                        },
                        new
                        {
                            V = "TZS"
                        },
                        new
                        {
                            V = "UAH"
                        },
                        new
                        {
                            V = "UGX"
                        },
                        new
                        {
                            V = "USD"
                        },
                        new
                        {
                            V = "USN"
                        },
                        new
                        {
                            V = "UYI"
                        },
                        new
                        {
                            V = "UYU"
                        },
                        new
                        {
                            V = "UYW"
                        },
                        new
                        {
                            V = "UZS"
                        },
                        new
                        {
                            V = "VES"
                        },
                        new
                        {
                            V = "VND"
                        },
                        new
                        {
                            V = "VUV"
                        },
                        new
                        {
                            V = "WST"
                        },
                        new
                        {
                            V = "XAF"
                        },
                        new
                        {
                            V = "XAG"
                        },
                        new
                        {
                            V = "XAU"
                        },
                        new
                        {
                            V = "XBA"
                        },
                        new
                        {
                            V = "XBB"
                        },
                        new
                        {
                            V = "XBC"
                        },
                        new
                        {
                            V = "XBD"
                        },
                        new
                        {
                            V = "XCD"
                        },
                        new
                        {
                            V = "XDR"
                        },
                        new
                        {
                            V = "XOF"
                        },
                        new
                        {
                            V = "XPD"
                        },
                        new
                        {
                            V = "XPF"
                        },
                        new
                        {
                            V = "XPT"
                        },
                        new
                        {
                            V = "XSU"
                        },
                        new
                        {
                            V = "XTS"
                        },
                        new
                        {
                            V = "XUA"
                        },
                        new
                        {
                            V = "XXX"
                        },
                        new
                        {
                            V = "YER"
                        },
                        new
                        {
                            V = "ZAR"
                        },
                        new
                        {
                            V = "ZMW"
                        },
                        new
                        {
                            V = "ZWL"
                        });
                });

            modelBuilder.Entity("_2c2p.Assignment.Data.Model.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("_2c2p.Assignment.Data.Model.TransactionStatus", b =>
                {
                    b.Property<string>("V")
                        .HasColumnType("VARCHAR(8)")
                        .HasColumnName("Values");

                    b.HasKey("V");

                    b.ToTable("TransactionStatus");

                    b.HasData(
                        new
                        {
                            V = "APPROVED"
                        },
                        new
                        {
                            V = "REJECTED"
                        },
                        new
                        {
                            V = "DONE"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
